name: MSYS2
on: [push, pull_request]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v5
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >
            mingw-w64-ucrt-x86_64-git 
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-libtool
            mingw-w64-ucrt-x86_64-pkgconf
            mingw-w64-ucrt-x86_64-hidapi
            mingw-w64-ucrt-x86_64-libusb
            mingw-w64-ucrt-x86_64-libftdi
            mingw-w64-ucrt-x86_64-libjaylink
            mingw-w64-ucrt-x86_64-capstone
            unzip

      - name: install ftd2xx
        run: |
          mkdir -p downloads/
          curl -L https://archive.org/download/cdm-v-2.12/CDM%20v2.12.zip -o downloads/d2xx.zip
          unzip downloads/d2xx.zip -d downloads/d2xx
          cp downloads/d2xx/*/ftd2xx.h /ucrt64/include/
          cp downloads/d2xx/*/amd64/* /ucrt/lib/

      - name: bootstrap
        run: ./bootstrap

      - name: configure
        run: >
          ./configure 
            --prefix=/usr/local 
            --build=$MINGW_CHOST 
            --disable-werror 
            --disable-dependency-tracking 
            --enable-dummy 

      - name: build
        run: make

      - name: install
        run: |
          mkdir -p build
          make DESTDIR=build install

      - name: Publish OpenOCD packaged for windows
        uses: actions/upload-artifact@v4
        with:
          path: build